/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Astronaut({ modelPath = "/models/tenhun_falling_spaceman_fanart.glb", ...props }) {
  const group = useRef();
  // Load the GLTF generically so any model can be swapped in.
  const gltf = useGLTF(modelPath);
  // animations (if present) will be played
  const { animations } = gltf || {};
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (animations && animations.length > 0) {
      const first = animations[0]?.name;
      if (first) actions[first]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  useFrame(() => {
    if (group.current) group.current.position.y = ySpring.get();
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={props.rotation ?? [-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale ?? 0.3}
      position={props.position ?? [1.3, -1, 0]}
    >
      {/* render the whole scene so models with different node names still display */}
      <primitive object={gltf.scene} />
    </group>
  );
}

// preload default model for faster startup
useGLTF.preload("/models/tenhun_falling_spaceman_fanart.glb");
